steps:
  # Build the container image with build args
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'VITE_SUPABASE_URL=https://fjdkdoantfcwbnsqghlj.supabase.co'
      - '--build-arg'
      - 'VITE_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZqZGtkb2FudGZjd2Juc3FnaGxqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njc5OTU2OTUsImV4cCI6MjA4MzU3MTY5NX0.qsUusyb3yvWE9C4386VhmHhOm4qaFTFmzAHR2a_S2c0'
      - '-t'
      - 'gcr.io/$PROJECT_ID/david-irie-photographie:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/david-irie-photographie:latest'
      - '.'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/david-irie-photographie:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/david-irie-photographie:latest'

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'david-irie-photographie'
      - '--image'
      - 'gcr.io/$PROJECT_ID/david-irie-photographie:$COMMIT_SHA'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'

  # Check if uploadToBackblaze function was modified
  - name: 'gcr.io/cloud-builders/git'
    id: 'check-backblaze-changes'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if git diff --name-only $COMMIT_SHA~1 $COMMIT_SHA | grep -q "^cloud-functions/uploadToBackblaze/"; then
          echo "uploadToBackblaze modified - will deploy"
          echo "DEPLOY_BACKBLAZE=true" > /workspace/deploy_flags.env
        else
          echo "uploadToBackblaze not modified - skipping"
          echo "DEPLOY_BACKBLAZE=false" > /workspace/deploy_flags.env
        fi

  # Deploy Cloud Function: uploadToBackblaze (only if modified)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        source /workspace/deploy_flags.env
        if [ "$DEPLOY_BACKBLAZE" = "true" ]; then
          gcloud functions deploy uploadToBackblaze \
            --gen2 \
            --runtime=nodejs20 \
            --region=europe-west1 \
            --source=./cloud-functions/uploadToBackblaze \
            --entry-point=uploadToBackblaze \
            --trigger-http \
            --allow-unauthenticated \
            --set-env-vars B2_KEY_ID=005aad79fa06b9e0000000001,B2_APPLICATION_KEY=K00521ST3tfdiv/eP9IFfBxTsmkdovw,B2_BUCKET_NAME=david-irie-photo,B2_ENDPOINT=s3.us-east-005.backblazeb2.com,B2_REGION=us-east-005
        else
          echo "Skipping uploadToBackblaze deployment"
        fi

  # Check if uploadToCloudinary function was modified
  - name: 'gcr.io/cloud-builders/git'
    id: 'check-cloudinary-changes'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if git diff --name-only $COMMIT_SHA~1 $COMMIT_SHA | grep -q "^cloud-functions/uploadToCloudinary/"; then
          echo "uploadToCloudinary modified - will deploy"
          echo "DEPLOY_CLOUDINARY=true" >> /workspace/deploy_flags.env
        else
          echo "uploadToCloudinary not modified - skipping"
          echo "DEPLOY_CLOUDINARY=false" >> /workspace/deploy_flags.env
        fi

  # Deploy Cloud Function: uploadToCloudinary (only if modified)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        source /workspace/deploy_flags.env
        if [ "$DEPLOY_CLOUDINARY" = "true" ]; then
          gcloud functions deploy uploadToCloudinary \
            --gen2 \
            --runtime=nodejs20 \
            --region=europe-west1 \
            --source=./cloud-functions/uploadToCloudinary \
            --entry-point=uploadToCloudinary \
            --trigger-http \
            --allow-unauthenticated
        else
          echo "Skipping uploadToCloudinary deployment"
        fi

  # Check if sendEmail function was modified
  - name: 'gcr.io/cloud-builders/git'
    id: 'check-email-changes'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if git diff --name-only $COMMIT_SHA~1 $COMMIT_SHA | grep -q "^cloud-functions/sendEmail/"; then
          echo "sendEmail modified - will deploy"
          echo "DEPLOY_EMAIL=true" >> /workspace/deploy_flags.env
        else
          echo "sendEmail not modified - skipping"
          echo "DEPLOY_EMAIL=false" >> /workspace/deploy_flags.env
        fi

  # Deploy Cloud Function: sendEmail (only if modified)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        source /workspace/deploy_flags.env
        if [ "$DEPLOY_EMAIL" = "true" ]; then
          gcloud functions deploy sendEmail \
            --gen2 \
            --runtime=nodejs20 \
            --region=europe-west1 \
            --source=./cloud-functions/sendEmail \
            --entry-point=sendEmail \
            --trigger-http \
            --allow-unauthenticated
        else
          echo "Skipping sendEmail deployment"
        fi

images:
  - 'gcr.io/$PROJECT_ID/david-irie-photographie:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/david-irie-photographie:latest'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
